<?php

// Generated by Haxe 3.4.7
class utils_ErrorMessage {
	public function __construct(){}
	static function create($who, $became, $target) {
		$value = haxe_Json::phpJsonEncode($target, null, null);
		switch($became) {
		case "found":{
			return "Not found " . _hx_string_or_null($value) . " in " . _hx_string_or_null($who) . ".";
		}break;
		case "specify":{
			return "Please specify " . _hx_string_or_null($value) . " in " . _hx_string_or_null($who) . ".";
		}break;
		}
	}
	function __toString() { return 'utils.ErrorMessage'; }
}
