<?php

// Generated by Haxe 3.4.7
class db_Connecter {
	public function __construct(){}
	static function init() {
		db_DBManager::init();
	}
	static function getUserList($params) {
		$user = new db_table_User();
		return Main::createResponse("success", $user->getList(null, null, null));
	}
	static function setUser($params) {
		$user = new db_table_User();
		$user->setRow($params);
		return Main::createResponse("success", $user->getList(null, null, null));
	}
	function __toString() { return 'db.Connecter'; }
}
