<?php

// Generated by Haxe 3.4.7
class db_table_Post extends db_table_Table {
	public function __construct() { if(!php_Boot::$skip_constructor) {
		$_g = new haxe_ds_StringMap();
		$_g->set("id", "id");
		$_g->set("user_id", "user_id");
		$_g->set("text", "text");
		$_g->set("schedule_datetime", "schedule_datetime");
		$_g->set("created_datetime", "created_datetime");
		$_g->set("updated_datetime", "updated_datetime");
		$_g->set("is_active", "is_active");
		parent::__construct("post",$_g);
	}}
	static $BASIC_COLUMNS;
	function __toString() { return 'db.table.Post'; }
}
db_table_Post::$BASIC_COLUMNS = (new _hx_array(array("id", "user_id", "text", "schedule_datetime")));
