<?php

// Generated by Haxe 3.4.7
class Lambda {
	public function __construct(){}
	static function harray($it) {
		$a = new _hx_array(array());
		{
			$i = $it->iterator();
			while($i->hasNext()) {
				$i1 = $i->next();
				$a->push($i1);
				unset($i1);
			}
		}
		return $a;
	}
	function __toString() { return 'Lambda'; }
}
